name: Mirror to GitHub

on:
  push:
    branches: [master]

jobs:
  mirror:
    runs-on: docker
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Push to GitHub
        run: |
          git remote add github https://${{ secrets.GHTOKEN }}@github.com/Raiden129/Beacon.git || true
          git push github master --force
